config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :admins
  resources :locations
  resources :courses
  resources :instructors
  resources :students

  post '/locations/:id', to: 'courses#remove', as: 'remove_course'

  post '/locations/:id', to: 'instructors#remove', as: 'remove_instructor'

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :password
  validates :password, confirmation: true
  before_save :encrypt_password

  validates_uniqueness_of :email, case_sensitive: false
  validates_presence_of :email
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    admin = Admin.where(email: email).first
    if admin && admin.password_hash == BCrypt::Engine.hash_secret(password, admin.password_salt)
      admin
    else
      nil
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :locations
  has_many :instructors
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :course
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :courses
  has_many :instructors
  has_many :students

  # def find_instructors(id)
  #   SELECT DISTINCT "instructors".* FROM "locations" WHERE ("instructors"."location_id" = id);
  # end
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :course
  belongs_to :instructor
  belongs_to :location
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admin = Admin.new
  end

  def new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      flash[:notice] = 'Welcome #{@admin.email}'
      redirect_to courses_path
    else
      flash[:alert] = 'There was a problem creating your account'
      redirect_to :back
    end
  end

  private
  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def current_admin
    session[:admin_id] ? Admin.find(session[:admin_id]) : nil

    # @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  helper_method :current_admin
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, except:[:index, :new, :create]

  def index
    @courses = Course.all
    @course = Course.new
    @locations = Location.all
  end


  def new
    @course = Course.new
    @locations = Location.all
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "#{@course.name} has been added"
      redirect_to @course
    else
      flash[:alert] = 'There was a problem creating that course'
      render :new
    end
  end

  def show
    @locations = @course.locations
    p "#{@locations.first} ******************"
    @instructors = @course.instructors
  end

  def edit
  end

  def remove
    @course.location_id = nil
    render nothing: true
  end

  def destroy
    if @course.destory
      flash[:notice] = 'This course has been deleted'
      redirect_to :index
    else
      flash[:alert] = 'There was a problem deleting that course'
      redirect_to @course
    end
  end


  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :location_id)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, except:[:index, :new, :create]

  def index
    @instructors = Instructor.all
    @instructor = Instructor.new
    @locations = Location.all
    @courses = Course.all
  end

  def new
  end

  def show
    @course = Course.find(@instructor.course_id)
    @location = Location.find(@instructor.location_id)
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      flash[:notice] = "#{@instructor.name} has been successfully created"
      redirect_to @instructor
    else
      flash[:alert] = 'There was a problem creating that instructor'
      render :index
    end
  end

  def edit
  end

  def remove
    @instructor.location_id = nil
    render nothing: true
  end

  def update
  end

  private
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(:name, :location_id, :course_id, :email)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, except:[:index, :new, :create]

  def index
    @locations = Location.all
    @location = Location.new
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = 'The new location has been successfully saved'
      redirect_to @location
    else
      flash[:alert] = 'There was a problem saving that location'
      render :new
    end
  end

  def show
    @courses = @location.courses.all
    @instructors = @location.instructors
  end

  def edit
  end

  def update
  end

  def destroy
    if @location.destory
      flash[:notice] = 'The location has been deleted'
      redirect_to :index
    else
      flash[:alert] = 'There was a problem deleting that location'
      redirect_to @location
    end
  end

  private
  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.authenticate(params[:email], params[:password])
    if @admin
      flash[:notice] = 'You have been logged in'
      session[:admin_id] = @admin.id
      redirect_to '/'
    else
      flash[:alert] = 'There was problem logging you in'
      redirect_to signin_path
    end
  end

  def destroy
    session[:admin_id] = nil
    flash[:notice] = 'You have been logged out successfully'
    redirect_to '/'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, except:[:index, :new, :create]

  def index
    @student = Student.new
    @students = Student.all
    @locations = Location.all
    @courses = Course.all
    @instructors = Instructor.all
  end

  def new
  end

  def show
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "#{@student.name} was successfully created"
      redirect_to @student
    else
      flash[:alert] = 'There was a problem creating that student'
      render :index
    end
  end

  def update

  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :location_id, :course_id, :instructor_id, :google_q, :html_q, :css_q, :js_q, :jq_q, :command_q, :git_q, :ruby_q, :sinatra_q, :rails_q, :mvc_q, :db_q, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_admin
    session[:admin_id] ? Admin.find(session[:admin_id]) : nil
    #
    # @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_new.html.erb
<%= form_for @course do |f|  %>
  <%= f.text_field :name %>
  <br>

  <%= f.select(:location_id) do %>
    <% @locations.each do |c| %>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <br>

  <%= f.submit 'Create a new course' %>
<% end %>

app/views/courses/index.html.erb
<%= render partial: 'new' %>

<h2>
  Courses
</h2>

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to "#{course.name}", course_path(course.id) %>
    </li>
  <% end %>
</ul>

app/views/courses/show.html.erb
<h1>
  <%= @course.name %>
</h1>


</p>

<ul>
  <% @locations.each do |loc| %>
    <li>
      <%= link_to "#{loc.name}", location_path(loc.id)  %>
    </li>
    <ul>
      <% @instructors.each do |instr| %>
        <% if loc.id == instr.location_id %>
          <li>
            <%= instr.name %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</ul>

app/views/instructors/_new.html.erb
<%= form_for @instructor do |f| %>
  <%= f.text_field :name, placeholder: 'instructor name' %>
  <br>
  <%= f.email_field :email, placeholder: 'instructor email' %>
  <br>
  <%= f.select(:location_id) do %>
    <% @locations.each do |c| %>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <br>

  <%= f.select(:course_id) do %>
    <% @courses.each do |c| %>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <br>
  <%= f.label 'Is a TA?' %>

  <%= f.check_box :ta %>
  <br>
  <%= f.submit 'Create a new instructor' %>
<% end %>

app/views/instructors/index.html.erb
<%= render partial: 'new' %>

<h2>
  Instructors
</h2>

<ul>
  <% @instructors.each do |instr| %>
    <li>
      <%= link_to "#{instr.name}", instructor_path(instr.id) %>

      <% if instr.ta %>
        <span> (TA)</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/instructors/show.html.erb
<h1>
  <%= @instructor.name %>
</h1>

<p>
  <%= link_to "#{@course.name}", course_path(@course.id) %>
</p>

<p>
  <%= link_to "#{@location.name}", location_path(@location.id) %>
</p>

<% if @instructor.ta %>
  <p>
    TA
  </p>
<% end %>

app/views/locations/_new.html.erb
<%= form_for @location do |f| %>
  <%= f.text_field :name, placeholder: 'Location name' %>
  <br>
  <%= f.submit 'Create a new location' %>
<% end %>

app/views/locations/edit.html.erb
<%= render 'new' %>

<h2>
  Courses at this location
</h2>
<ul>

<% @location.courses.each do |course| %>
  <li>
    <%= link_to "#{course.name}", course_path(course.id) %>
    <%= link_to "X", remove_course_path(course.id) %>
  </li>
<% end %>
</ul>

<h2>
  Instructors at this location
</h2>


<ul>

<% @location.instructors.each do |instr| %>
  <li>
    <%= instr.name %>
    <%= link_to "X", remove_instructor_path(instr.id) %>
  </li>
<% end %>
</ul>

app/views/locations/index.html.erb
<%= render partial: 'new' %>

<ul>
  <% @locations.each do |loc| %>
    <li>
      <%= link_to "#{loc.name}", location_path(loc.id) %>
    </li>
  <% end %>
</ul>

app/views/locations/show.html.erb
<h1>
  <%= @location.name %>
</h1>

<p>
  <%= link_to 'Delete this location?', location_path(@location.id), method: :delete, data: {confirm: "Are you sure you want to delete #{@location.name}?"} %>
</p>

<p>
  <%= link_to 'Edit', edit_location_path(@location.id) %>
</p>

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to "#{course.name}", course_path(course.id) %>
    </li>

    <% @instructors.each do |instr| %>
      <% if course.id == instr.course_id %>
        <ul>
          <li>
            <%= link_to "#{instr.name}", instructor_path(instr.id) %>

            <% if instr.ta %>
              <span> (TA)</span>
            <% end %>
          </li>
        </ul>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/students/_new.html.erb
<%= form_for @student do |f| %>
  <%= f.text_field :name, placeholder: 'student name' %>
  <br>
  <%= f.email_field :email, placeholder: 'student email' %>
  <br>
  <%= f.select(:location_id) do %>
    <% @locations.each do |c| %>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <br>

  <%= f.select(:course_id) do %>
    <% @courses.each do |c| %>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <br>

  <%= f.select(:instructor_id) do %>
    <% @instructors.each do |c| %>
      <% if c.ta == false %>
        <%= content_tag(:option, c.name, value: c.id) %>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <%= f.submit 'Create a new student' %>
<% end %>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<%= render partial: 'new' %>

<% if @students.length > 0 %>
  <% @students.each do |student| %>
    <%= link_to "#{student.name}", student_path(student.id) %>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>